server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://localhost:3306/springcloud_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
  cloud: #consul注册中心地址
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register-health-check: false
